### ISSUE TITLE
no spook command

### ISSUE THREAD

**Issue by of-ravens-claw** [Uplodading-Team/darkness-bot#2]
hello pls add a spook command so I can ping u everyday

**Comment by AjaxR0** [comment]
victor ur stupid and gae thank u

**Comment by Rodolfoam3** [comment]
### we'll think about that
_jk_

**Comment by AjaxR0** [comment]
rodolfo update the beta when

**Comment by of-ravens-claw** [comment]
> 
> 
> victor ur stupid and gae thank u

no U

**Comment by AjaxR0** [comment]
> No u
ur mum

**Comment by Rodolfoam3** [comment]
Won't happen, closing.
