### ISSUE TITLE
Moderation Commands

### ISSUE THREAD

**Issue by Rodolfoam3** [Uplodading-Team/darkness-bot#6]
- [x] Warning system

- [x] Mute system

- [x] Kick command

- [x] Ban command

> More soon

(@Dexteroide will update this soon)

**Comment by AjaxR0** [comment]
y do u keep pinging me
```
b
```
************@@Rodolfoam3 ************

**Comment by Rodolfoam3** [comment]
> y do u keep pinging me

bcs yes

**Comment by AjaxR0** [comment]
> > y do u keep pinging me
> 
> bcs yes
Banned, bjs no cu

**Comment by Rodolfoam3** [comment]
> Banned, bjs no cu

vem banir (try and runnnn)

**Comment by AjaxR0** [comment]
> > Banned, bjs no cu
> 
> vem banir (try and runnnn)

- [ ] command to wake @Rodolfoam3 from sleep

**Comment by AjaxR0** [comment]
> > Banned, bjs no cu
> 
> vem banir (try and runnnn)

- [ ] command to wake @Rodolfoam3 from sleep

**Comment by AjaxR0** [comment]
eta @Rodolfoam3

**Comment by AjaxR0** [comment]
done
